### ISSUE TITLE
Build is breaking under go older than 1.4

### ISSUE THREAD

**Issue by manishrjain** [valyala/gorpc#11]
as of a pull right now.

../../../valyala/gorpc/client.go:553: undefined: atomic.Value
../../../valyala/gorpc/server.go:187: undefined: atomic.Value
../../../valyala/gorpc/server.go:240: undefined: atomic.Value

**Comment by valyala** [comment]
Gorpc requires at least go1.4, since atomic.Value has been appeared in this release. See `Minor changes to the library` in https://golang.org/doc/go1.4 .

Though it is possible to use something else instead of atomic.Value in order to gain backwards compatibility with older go releases, but I doubt it is good time investment :)

BTW, why you cannot migrate to go1.5 or at least to go1.4?

**Comment by valyala** [comment]
Closing this issue, since gorpc won't be backported to go versions older than 1.4
